// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using API.Models.v1;
//
//    var loginBodyPatch = LoginBodyPatch.FromJson(jsonString);

namespace API.Models.v1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class LoginBodyPatch
    {
        [JsonProperty("userName", NullValueHandling = NullValueHandling.Ignore)]
        public string UserName { get; set; }

        [JsonProperty("password", NullValueHandling = NullValueHandling.Ignore)]
        public string Password { get; set; }
    }

    public partial class LoginBodyPatch
    {
        public static LoginBodyPatch FromJson(string json) => JsonConvert.DeserializeObject<LoginBodyPatch>(json, API.Models.v1.Converter.Settings);
        public LoginBodyPatch(string userName,string password)
        {
            this.UserName = userName;
            this.Password = password;
        }
    }
}
