// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using API.Models.v1;
//
//    var shoppingCart = ShoppingCart.FromJson(jsonString);

namespace API.Models.v1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ShoppingCart : CryWolf
    {
        [JsonProperty("accountNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountNumber { get; set; }

        [JsonProperty("accountType", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountType { get; set; }

        [JsonProperty("invoiceIds", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> InvoiceIds { get; set; }

        [JsonProperty("cartTotal", NullValueHandling = NullValueHandling.Ignore)]
        public long? CartTotal { get; set; }
    }

    public partial class ShoppingCart
    {
        public static ShoppingCart FromJson(string json) => JsonConvert.DeserializeObject<ShoppingCart>(json, API.Models.v1.Converter.Settings);
    }

    //public static class Serialize
    //{
    //    public static string ToJson(this ShoppingCart self) => JsonConvert.SerializeObject(self, API.Models.v1.Converter.Settings);
    //}

    //internal static class Converter
    //{
    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //    {
    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //        DateParseHandling = DateParseHandling.None,
    //        Converters =
    //        {
    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //        },
    //    };
    //}
}
