// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using API.Models.v1;
//
//    var sendAutoLetter = SendAutoLetter.FromJson(jsonString);

namespace API.Models.v1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SendAutoLetterBody
    {
        [JsonProperty("invoiceId", NullValueHandling = NullValueHandling.Ignore)]
        public int InvoiceId { get; set; }

        [JsonProperty("letterName", NullValueHandling = NullValueHandling.Ignore)]
        public string LetterName { get; set; }

        [JsonProperty("accountType", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountType { get; set; }

        [JsonProperty("accountNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountNumber { get; set; }
    }

    public partial class SendAutoLetterBody
    {
        public static SendAutoLetterBody FromJson(string json) => JsonConvert.DeserializeObject<SendAutoLetterBody>(json, API.Models.v1.Converter.Settings);

        public SendAutoLetterBody(int invoiceId, string letterName, string accountType, string accountNumber)
        {
            this.InvoiceId = invoiceId;
            this.LetterName = letterName;
            this.AccountType = accountType;
            this.AccountNumber = accountNumber;
        }
    }

    //public static class Serialize
    //{
    //    public static string ToJson(this SendAutoLetter self) => JsonConvert.SerializeObject(self, API.Models.v1.Converter.Settings);
    //}

    //internal static class Converter
    //{
    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //    {
    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //        DateParseHandling = DateParseHandling.None,
    //        Converters =
    //        {
    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //        },
    //    };
    //}
}
