// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using API.Models.v1;
//
//    var sendAutoLetter = SendAutoLetter.FromJson(jsonString);

namespace API.Models.v1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SendAutoLetter
    {
        [JsonProperty("invoiceIdsCreated", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> InvoiceIdsCreated { get; set; }

        [JsonProperty("informationMessages", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> InformationMessages { get; set; }
    }

    public partial class SendAutoLetter
    {
        public static SendAutoLetter FromJson(string json) => JsonConvert.DeserializeObject<SendAutoLetter>(json, API.Models.v1.Converter.Settings);
    }

    //public static class Serialize
    //{
    //    public static string ToJson(this SendAutoLetter self) => JsonConvert.SerializeObject(self, API.Models.v1.Converter.Settings);
    //}

    //internal static class Converter
    //{
    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //    {
    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //        DateParseHandling = DateParseHandling.None,
    //        Converters =
    //        {
    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //        },
    //    };
    //}
}
