// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using API.Models.v1;
//
//    var paymentResponsePut = PaymentResponsePut.FromJson(jsonString);

namespace API.Models.v1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PaymentPUT
    {
        [JsonProperty("invoiceIdsCreated", NullValueHandling = NullValueHandling.Ignore)]
        public List<long> InvoiceIdsCreated { get; set; }

        [JsonProperty("informationMessages", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> InformationMessages { get; set; }

        [JsonProperty("errorId", NullValueHandling = NullValueHandling.Ignore)]
        public long? ErrorId { get; set; }

        [JsonProperty("errorMessage", NullValueHandling = NullValueHandling.Ignore)]
        public string ErrorMessage { get; set; }

        [JsonProperty("autoActionsToApprove", NullValueHandling = NullValueHandling.Ignore)]
        public List<AutoActions> AutoActionsToApprove { get; set; }

        [JsonProperty("autoActionsPerformed", NullValueHandling = NullValueHandling.Ignore)]
        public List<AutoActions> AutoActionsPerformed { get; set; }
    }

    public partial class AutoActions
    {
        [JsonProperty("invoiceId", NullValueHandling = NullValueHandling.Ignore)]
        public int InvoiceId { get; set; }

        [JsonProperty("letterName", NullValueHandling = NullValueHandling.Ignore)]
        public string LetterName { get; set; }

        [JsonProperty("accountType", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountType { get; set; }

        [JsonProperty("accountNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string AccountNumber { get; set; }
    }

    public partial class PaymentPUT
    {
        public static PaymentPUT FromJson(string json) => JsonConvert.DeserializeObject<PaymentPUT>(json, API.Models.v1.Converter.Settings);
    }

    //public static class Serialize
    //{
    //    public static string ToJson(this PaymentResponsePut self) => JsonConvert.SerializeObject(self, API.Models.v1.Converter.Settings);
    //}

    //internal static class Converter
    //{
    //    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //    {
    //        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //        DateParseHandling = DateParseHandling.None,
    //        Converters =
    //        {
    //            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //        },
    //    };
    //}
}
