//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    public sealed partial class Utils : global::System.Configuration.ApplicationSettingsBase {
        
        private static Utils defaultInstance = ((Utils)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Utils())));
        
        public static Utils Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("grid")]
        public string RUN_LOCATION {
            get {
                return ((string)(this["RUN_LOCATION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WRITE_TO_SQL {
            get {
                return ((bool)(this["WRITE_TO_SQL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crywolf-preprod.ps.lcl")]
        public string DBHOST_GRID {
            get {
                return ((string)(this["DBHOST_GRID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cw-qa-tx-da")]
        public string DBNAME_GRID {
            get {
                return ((string)(this["DBNAME_GRID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trunk")]
        public string APP_VERSION {
            get {
                return ((string)(this["APP_VERSION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://crywolf-preprod.ps.lcl:8000/TX-Dallas")]
        public string URL_QA {
            get {
                return ((string)(this["URL_QA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Program Files (x86)\\\\Windows Application Driver\\\\WinAppDriver.exe")]
        public string WINAPPDRIVER_PATH {
            get {
                return ((string)(this["WINAPPDRIVER_PATH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crywolf-preprod.ps.lcl")]
        public string DBHOST_LOCAL {
            get {
                return ((string)(this["DBHOST_LOCAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cw-qa-tx-da")]
        public string DBNAME_LOCAL {
            get {
                return ((string)(this["DBNAME_LOCAL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://crywolf-citizenportal.azurewebsites.net")]
        public string URL_AZURE_QA {
            get {
                return ((string)(this["URL_AZURE_QA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("crywolf-sql")]
        public string DBHOST_AZURE {
            get {
                return ((string)(this["DBHOST_AZURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cw-qa-nc-hp-191")]
        public string DBNAME_AZURE {
            get {
                return ((string)(this["DBNAME_AZURE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QA")]
        public string BUILD_CONFIG {
            get {
                return ((string)(this["BUILD_CONFIG"]));
            }
        }
    }
}
